# 🔍 Tech keywords
TECH_KEYWORDS = {
    "python": ["python"],
    "sql": ["sql"],
    "spark": ["spark", "pyspark"],
    "hadoop": ["hadoop", "hdfs", "mapreduce"],
    "airflow": ["airflow", "apache airflow"],
    "dbt": ["dbt", "data build tool"],
    "kafka": ["kafka", "redpanda", "confluent"],
    "flink": ["flink", "apache flink"],
    "snowflake": ["snowflake"],
    "clickhouse": ["clickhouse"],
    "aws": ["aws", "s3", "glue", "lambda", "redshift", "emr", "athena", "kinesis"],
    "gcp": ["gcp", "bigquery", "dataflow", "pubsub", "dataproc", "composer"],
    "azure": ["azure", "synapse", "databricks", "event hubs"],
    "docker": ["docker", "container"],
    "kubernetes": ["kubernetes", "k8s", "eks", "gke", "aks"],
    "etl": ["etl", "elt", "data pipeline", "data pipelines", "extract transform load"],
    "apache_nifi": ["nifi", "apache nifi"],
    "terraform": ["terraform", "infrastructure as code", "iac"],
    "ci_cd": ["ci/cd", "ci-cd", "jenkins", "github actions", "gitlab ci", "circleci"],
    "nosql": ["nosql", "mongodb", "cassandra", "dynamodb", "redis"],
    "postgresql": ["postgresql", "postgres"],
    "rest_api": ["rest api", "restful", "api gateway"],
    "graph": ["neo4j", "graph database", "janusgraph"],
    "metrics": ["prometheus", "grafana", "monitoring", "alerting"],
    "elastic": ["elasticsearch", "elk", "kibana", "logstash"],
    "airbyte": ["airbyte"],
    "dagster": ["dagster"],
    "great_expectations": ["great expectations", "data quality", "data validation"],
    "data_mesh": ["data mesh"],
    "data_lake": ["data lake", "lakehouse", "delta lake"],
    "delta_lake": ["delta lake"],
    "spark_streaming": ["spark streaming", "structured streaming"],
    "kinesis": ["kinesis", "aws kinesis"],
    "dbt_utils": ["dbt-utils"],
    "pentaho": ["pentaho"],
    "talend": ["talend"],
    "apache_beam": ["apache beam"],
    "hive": ["hive", "apache hive"],
    "presto": ["presto", "prestodb", "trino"],
    "druid": ["druid", "apache druid"],
    "zeppelin": ["zeppelin", "apache zeppelin"],
    "jupyter": ["jupyter", "notebook"],
    "hue": ["hue"],
}